services:
  postgres:
    container_name: next-full-stack-postgres
    image: postgres:17.0-alpine
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: next_full_stack
      POSTGRES_PASSWORD: next_full_stack
      POSTGRES_DB: next_full_stack
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-full-stack
    image: next-full-stack
    restart: always
    ports:
      - '127.0.0.1:8080:3000'
    env_file:
      - .env.example
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data:
